version: "3.0"

x-common-config: &common-config
  deploy:
    restart_policy:
      condition: any
    mode: replicated
    replicas: 1

services:
  rasa:
    image: rasa/rasa:latest-full
    user: "root"
    networks: ["rasa-network"]
    volumes:
      - "./app/rasa:/app/"
    command: >
      run 
      --endpoints endpoints.yml
      --remote-storage aws
      --enable-api
      --cors "*"
      --debug
    environment:
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_ENDPOINT_URL=http://minio:9000
      - BUCKET_NAME=models
    depends_on:
      - mongo-rs0-2
      - mongo-rs0-1
      - mongo-rs0-3

  action_server:
    image: rasa/rasa-sdk:latest
    networks: ["rasa-network"]
    volumes:
      - "./app/actions:/app/actions"

  redis:
    image: redis:latest
    networks: ["rasa-network"]

  nlg:
    entrypoint: ["python"]
    image: nlg_server
    networks: ["rasa-network"]
    user: "root"
    build:
      context: ./app/nlg
    volumes:
      - ./app/domain/domain.yml:/nlg/domain.yml
    command: nlg_server.py --port 5056 --domain ./domain.yml

  api:
    networks: ["rasa-network"]
    build: ./app/api
    volumes:
      - ./app/api:/api
      - ./app/domain/domain.yml:/api/domain.yml
    depends_on:
      - mongo-rs0-1
      - mongo-rs0-2
      - mongo-rs0-3
      - rasa

  nginx:
    networks: ["rasa-network"]
    build: ./app/nginx
    ports:
      - "8080:8080"
    depends_on:
      - rasa
      - api

  mongo-rs0-1:
    image: mongo
    networks: ["rasa-network"]
    command: --replSet rs0 --port 30001 --bind_ip_all
    volumes:
      - ./app/mongo/mongo-rs0-1:/data/db
    depends_on:
      - mongo-rs0-2
      - mongo-rs0-3
    environment:
      MONGO_INITDB_DATABASE: rasa

  mongo-rs0-2:
    image: mongo
    networks: ["rasa-network"]
    command: --replSet rs0 --port 30002 --bind_ip_all
    volumes:
      - ./app/mongo/mongo-rs0-2:/data/db
    environment:
      MONGO_INITDB_DATABASE: rasa

  mongo-rs0-3:
    image: mongo
    networks: ["rasa-network"]
    command: --replSet rs0 --port 30003 --bind_ip_all
    volumes:
      - ./app/mongo/mongo-rs0-3:/data/db
    environment:
      MONGO_INITDB_DATABASE: rasa

  mongo-rs-starter:
    image: mongo-rs-starter
    networks: ["rasa-network"]
    depends_on:
      - mongo-rs0-1

  minio:
    image: minio/minio
    networks: ["rasa-network"]
    command: ["server", "/storage", "--console-address", ":9001"]
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./app/minio/storage:/storage

networks: { rasa-network: {} }
