version: "3.0"

services:
  rasa:
    image: rasa/rasa:latest-full
    user: "root"
    networks: ["rasa-network"]
    volumes:
      - "./app/rasa:/app/"
    command: >
      run 
      --endpoints endpoints.yml
      -m models
      --enable-api
      --cors "*"
      --debug

  action_server:
    image: rasa/rasa-sdk:latest #talvez criar imagem do servidor de actions ao invés disso
    networks: ["rasa-network"]
    volumes:
      - "./app/actions:/app/actions"

  postgres:
    image: postgres:latest
    networks: ["rasa-network"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: rasa

  redis:
    image: redis:latest
    networks: ["rasa-network"]

  nlg:
    entrypoint: ["python"]
    image: nlg_server
    networks: ["rasa-network"]
    user: "root"
    build:
      context: ./app/nlg
    volumes:
      - ./app/data:/nlg/data
    command: nlg_server.py --port 5056 --domain ./data/domain.yml

  api:
    networks: ["rasa-network"]
    build: ./app/api
    volumes:
      - ./app/api:/api

  nginx:
    networks: ["rasa-network"]
    restart: on-failure
    build: ./app/nginx
    volumes:
      - ./app/nginx:/nginx
    ports:
      - "8080:8080"
    depends_on:
      - rasa
      - api

  #factoresbot_api

  #model_server

  #logging

  #nginx

networks: { rasa-network: {} }
