version: "3.0"

services:
  rasa:
    image: rasa/rasa:latest-full
    user: "root"
    networks: ["rasa-network"]
    ports:
      - "5005:5005"
    volumes:
      - "./app/:/app/"
    command: >
      run 
      --endpoints endpoints.yml
      -m models
      --enable-api
      --cors "*"

  action_server:
    image: rasa/rasa-sdk:latest
    networks: ["rasa-network"]
    ports:
      - "5055:5055"
    volumes:
      - "./app/actions:/app/actions"

  postgres:
    image: postgres:latest
    networks: ["rasa-network"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: rasa
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks: ["rasa-network"]

networks: { rasa-network: {} }
