version: "3.0"

services:
  rasa:
    image: rasa/rasa:latest-full
    user: "root"
    networks: ["rasa-network"]
    ports:
      - "5005:5005"
    volumes:
      - "./app/rasa:/app/"
    command: >
      run 
      --endpoints endpoints.yml
      -m models
      --enable-api
      --cors "*"
      --debug

  action_server:
    image: rasa/rasa-sdk:latest #talvez criar imagem do servidor de actions ao invés disso
    networks: ["rasa-network"]
    ports:
      - "5055:5055"
    volumes:
      - "./app/actions:/app/actions"

  postgres:
    image: postgres:latest
    networks: ["rasa-network"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: rasa

  redis:
    image: redis:latest
    networks: ["rasa-network"]

  nlg:
    entrypoint: ["python"]
    image: nlg_server
    networks: ["rasa-network"]
    user: "root"
    build:
      context: ./app/nlg
    volumes:
      - ./app/data:/nlg/data
    ports:
      - "5056:5056"
    command: nlg_server.py --port 5056 --domain ./data/domain.yml

  #model_server

  #logging

  #factoresbot_api

  #nginx

networks: { rasa-network: {} }
